[tools]
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"
cargo-binstall = "latest"
uv = "latest"

fzf = "latest"
neovim = "latest"
usage = "latest"
shellcheck = "latest"

# AI tools
claude = "latest"
codex = "latest"
gemini-cli = "latest"

# Rust tools
"cargo:cargo-cache" = "latest"              # display information on $CARGO_HOME
"cargo:cargo-generate" = "latest"           # create a rust project from a git as template
"cargo:cargo-update" = "latest"             # `cargo install-update`
"cargo:vmtest" = "latest"

# Rust tools managed by pacman
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:hyperfine" = "latest"
"cargo:intentrace" = "latest"
"cargo:jless" = "latest"
"cargo:https://github.com/aome510/hackernews-TUI" = "latest"
"cargo:https://github.com/fioncat/otree" = "latest"
"cargo:https://github.com/ck-zhang/reddix" = "latest"
"cargo:https://github.com/ckaznable/tenki" = "latest"

# Node tools
"npm:mcp-hub" = "latest"

# Python tools
"pipx:drgn" = "latest"
"pipx:neovim-remote" = "latest"
"pipx:shell-functools" = "latest"           # shell utilities, https://github.com/sharkdp/shell-functools
"pipx:terminaltexteffects" = "latest"       # terminal visual effects enginel, https://github.com/ChrisBuilds/terminaltexteffects
"pipx:virtme-ng" = "latest"

[settings]
auto_install = false
env_file = ".env"
exec_auto_install = false
idiomatic_version_file_enable_tools = []
trusted_config_paths = ["~/.config/mise/config.toml"]

[settings.cargo]
binstall = true

[settings.pipx]
uvx = true

[settings.rust]
# cargo_home = "~/.local/share/cargo"
# rustup_home = "~/.local/share/rustup"

[settings.status]
missing_tools = "never"                     # if_other_versions_installed, never, always
show_env = true
